# Generated by Django 5.1.2 on 2024-11-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='default title', max_length=300),
            preserve_default=False,
        ),
    ]
