version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - backend

  django:
    build:
      context: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - backend
    volumes:
      - .:/app 

  celery_worker:
    build:
      context: .
    container_name: celery_worker
    command: celery -A config.celery_app worker -l info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - backend
    volumes:
      - .:/app

networks:
  backend:
    driver: bridge
