version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - backend

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka_server
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INSIDE://kafka:19092,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:19092,OUTSIDE://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - backend
    depends_on:
      - zookeeper

  django:
    build:
      context: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker
      - kafka
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BROKER_URL: kafka:9092
    networks:
      - backend
    volumes:
      - .:/app 

  celery_worker:
    build:
      context: .
    container_name: celery_worker
    command: celery -A config worker -l info
    depends_on:
      - redis
      - kafka
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - KAFKA_BROKER_URL=kafka:9092
    networks:
      - backend
    volumes:
      - .:/app

  kafka_worker:
    build:
      context: .
    container_name: kafka_worker
    command: celery -A config worker -Q kafka-celery --concurrency=1 --loglevel=info
    depends_on:
      - redis
      - kafka
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - KAFKA_BROKER_URL=kafka:9092
    networks:
      - backend
    volumes:
      - .:/app

  celery_beat:
    build:
      context: .
    container_name: celery_beat
    command: celery -A config beat -l info
    depends_on:
      - redis
      - celery_worker
      - kafka_worker
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - backend
    volumes:
      - .:/app

networks:
  backend:
    driver: bridge
